# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site title
title: "The Salty Korean"

# A description of your site for social meta tag, search engines, and feed.xml
description: "Randy Walker blog"

# Tagline near the site title
tagline: "Randy Walker's thoughts, stories and ideas. President of Harvest Data Corp, Microsoft MVP award winner, ASP Insider and tech enthusiast"

# The subpath of your site, e.g. /blog, for generating urls
baseurl:

sass:
  sass_dir: _sass

# The base hostname & protocol of your site for where absolute urls are needed
#url: ""

# Site navigation - each item must have a title and a url.
navigation:
- text: Home
  url: /
- text: About
  url: /about/
- text: Style Guides
  url: /style-guide/
- text: Archives
  url: /tags/

# The shortname for your Disqus site to enable comments.
disqus:

# Author information - author info at the bottom of the post
author_name: "Randy Walker"
author_bio: "Randy is an entrepreneur, software developer, amateur photographer, speaker and influencer"
author_url:  "http://thesaltykorean.com"
author_location: "Bentonville, Arkansas, USA"
author_image: /images/RandyWalkerSquare.jpg

# Sidebar Add banner
banner_url: "https://thesaltykorean.com"
banner_image: images/banner.jpg

# Sidebar newsletter widget - add your form action url for MailChimp signup form here
#mailchimp_url: "//thesaltykorean.us3.list-manage.com/subscribe/post?u=78f1bab16028354caeb23aecd&amp;id=4a7330d117"

# Social links in the site footer
twitter_username: "TheSaltyKorean"
#facebook_username: "username"
#googleplus_username: "+username"
github_username: "TheSaltyKorean"
#codepen_username: "username"
#dribbble_uername: "username"
#medium_username: "@username"
instagram_username: "thesaltykorean"
#pinterest_username: "username"
linkedin_username: "RandyWalker1"
#weibo_username: "username"

# http://jekyllrb.com/docs/pagination/
paginate: 5
paginate_path: '/blog/page:num/'
plugins: [jekyll-paginate]

permalink: pretty
markdown: kramdown
kramdown:
    auto_ids: false
